### ISSUE TITLE
Mass loss calculation after running demo

### ISSUE THREAD

**Issue by kerstinvg** [mbarzegary/BioDeg#1]
Hello

I ran the demo screw model. However, I didn't receive a .vtk file, even tough I enabled it in the output section. I only got the single .vtu files and one .pvd file. 
Further, something went wrong with the mass loss calculation (see picture).
I followed the steps described in the manual. 

Thanks and Regards,
Kerstin 

![issue_mass_loss](https://user-images.githubusercontent.com/101254062/159247691-2ad26860-c6b5-444a-bfd6-66a525782800.PNG)

**Comment by mbarzegary** [comment]
hi Kerstin,

thank you for reporting this issue. the demo screw has a very small and unrealistic size (less than 1 millimeter) because it aimed to show the morphological changes of a device without needing a long simulation. so, as we can see in the graph, it has been totally degraded (100 percent mass loss) on T~2, and after that, what we see here is just numerical error. so I think I should add a criterion to the code to stop the simulation when the mass loss exceeds 99%. I should also clearly mention in the graph title that the mass loss is plotted in percentage.

regarding the vtk files: if I understood it correctly, you have one pvd file and many vtu files. the vtu files are actually vtk files, and since they are written per employed CPU core (more precisely saying, for each partition of the mesh), there is a pvd file as a container for paraview to read all the generated vtu files. so, if you open the pvd file in paraview (as demonstrated in the visualization videos), you should be able to view the simulation results.

**Comment by mbarzegary** [comment]
I fixed the issue as stated in the commits above. I think the confusion on the pvd file comes from a minor difference between the visualization videos and current format of the result files, so I updated the manual to clarify this difference https://github.com/mbarzegary/BioDeg-doc/commit/786f81ad047a0e5921ba16b5a2c0fa0bd00fbe62
